"""
app/modules/identity/domain/audit_events.py — Identity audit event definitions.

Every critical authentication, authorization, membership, or grant lifecycle
change emits one of these events to the transactional outbox table.
"""

from __future__ import annotations

from enum import Enum


class IdentityAuditEvent(str, Enum):
    USER_CREATED = "USER_CREATED"
    MEMBERSHIP_CREATED = "MEMBERSHIP_CREATED"
    MEMBERSHIP_SUSPENDED = "MEMBERSHIP_SUSPENDED"
    MEMBERSHIP_REVOKED = "MEMBERSHIP_REVOKED"
    GRANT_CREATED = "GRANT_CREATED"
    GRANT_REVOKED = "GRANT_REVOKED"
    SHARING_GRANT_CREATED = "SHARING_GRANT_CREATED"
    SHARING_GRANT_REVOKED = "SHARING_GRANT_REVOKED"
    SESSION_CREATED = "SESSION_CREATED"
    SESSION_REVOKED = "SESSION_REVOKED"
    SESSION_REVOKED_ALL = "SESSION_REVOKED_ALL"
    SESSION_IDLE_TIMEOUT = "SESSION_IDLE_TIMEOUT"
    AUTH_FAILED = "AUTH_FAILED"
    AUTHZ_DENIED = "AUTHZ_DENIED"
    CSRF_VALIDATION_FAILED = "CSRF_VALIDATION_FAILED"
    ORIGIN_VALIDATION_FAILED = "ORIGIN_VALIDATION_FAILED"
    OIDC_FLOW_FAILED = "OIDC_FLOW_FAILED"
    GRANT_AUTHORITY_DENIED = "GRANT_AUTHORITY_DENIED"
    ORG_SELECTED_MULTI_MEMBER = "ORG_SELECTED_MULTI_MEMBER"
