"""
ml-training/notebooks/train_cv_hazard_model.py — Module 1: CV Hazard Verification Training.

REAL TRAINING RUNS IN COLAB/KAGGLE, NOT HERE. This file is written as a plain
.py script (paste into a Colab cell-by-cell, or `%run` it) rather than a
committed .ipynb, since notebooks are hard to code-review as diffs.

By default this points at the tiny synthetic smoke-test dataset generated by
generate_synthetic_cv_dataset.py, which proves the Ultralytics API calls
below are wired correctly (data.yaml format, train()/val() signature,
export()) — it does NOT prove the model learns anything real. A model
trained on synthetic colored rectangles has zero ability to detect real
landslides, flooding, road damage, or tree falls.

To train for real:
  1. Source real imagery: AIDER, CrisisMMD, Landslide4Sense (see aiml
     developer.md §2 Module 1 for links), plus any custom NH-6 field photos.
  2. Label it in YOLO format for the 5 classes: LANDSLIDE, FLOOD_WATERLOGGING,
     ROAD_DAMAGE_CRACK, TREE_FALL, CLEAR_ROAD (Roboflow is the easiest
     annotation tool for this).
  3. Open this file in Google Colab with a T4 GPU runtime, set DATA_YAML_PATH
     to your real dataset's data.yaml, bump EPOCHS to 50-100, and run.
  4. Export to ONNX/FP16 and copy the .onnx artifact into
     backend/app/modules/ai/infrastructure/models/ for Phase 3.

Usage (smoke test only, CPU, this sandbox):
    python notebooks/train_cv_hazard_model.py
"""

from __future__ import annotations

from pathlib import Path

from ultralytics import YOLO

# Toggle this to a real dataset's data.yaml + higher epoch count when running
# in Colab with a GPU. Left pointed at the synthetic smoke-test set by default
# so this script is safe to run in the CPU-only dev sandbox.
DATA_YAML_PATH = Path(__file__).resolve().parent.parent / "data" / "synthetic_cv" / "data.yaml"
EPOCHS = 1  # Real training: 50-100 epochs on a GPU.
IMAGE_SIZE = 128  # Real training: 640 (Ultralytics default).
MODEL_VARIANT = "yolov8n.pt"  # Real training: yolov8x.pt for best accuracy.


def train_and_export() -> Path:
    if not DATA_YAML_PATH.exists():
        raise FileNotFoundError(
            f"{DATA_YAML_PATH} not found — run generate_synthetic_cv_dataset.py first "
            "for a smoke test, or point DATA_YAML_PATH at a real dataset."
        )

    model = YOLO(MODEL_VARIANT)
    results = model.train(
        data=str(DATA_YAML_PATH),
        epochs=EPOCHS,
        imgsz=IMAGE_SIZE,
        device="cpu",
        verbose=False,
        project=str(Path(__file__).resolve().parent.parent / "models"),
        name="cv_hazard_run",
        exist_ok=True,
    )
    print(f"Training complete. Results dir: {results.save_dir}")

    metrics = model.val(data=str(DATA_YAML_PATH), imgsz=IMAGE_SIZE, device="cpu", verbose=False)
    print(f"Validation mAP50: {metrics.box.map50:.4f}  (meaningless on synthetic data — smoke test only)")

    export_path = model.export(format="onnx")
    print(f"Exported ONNX model to {export_path}")
    return Path(export_path)


if __name__ == "__main__":
    train_and_export()
